"""empty message

Revision ID: e97982e2bbe5
Revises: 
Create Date: 2020-04-14 12:20:35.476306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97982e2bbe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deem',
    sa.Column('today', sa.DATE(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
